package reversi.apo;

import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.border.MatteBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JC
 */
public class fenetre extends javax.swing.JFrame {

    /**
     * Creates new form fenetre
     */
    public fenetre() {
            initComponents();
            Color color = new Color(0, 0, 0);
            grille.setShowHorizontalLines(true);
            grille.setShowVerticalLines(true);
            grille.setGridColor(Color.BLACK);
            grille.setRowHeight(100);
            plateau = new Plateau(grille, 1);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grille = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(810, 830));
        setResizable(false);

        grille.setBackground(new java.awt.Color(0, 153, 51));
        grille.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        grille.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grille.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grille.setEnabled(false);
        grille.setFocusable(false);
        grille.setMaximumSize(new java.awt.Dimension(800, 800));
        grille.setMinimumSize(new java.awt.Dimension(800, 800));
        grille.setSelectionBackground(new java.awt.Color(255, 255, 255));
        grille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grilleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(grille, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(grille, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        if (grille.getColumnModel().getColumnCount() > 0) {
            grille.getColumnModel().getColumn(0).setResizable(false);
            grille.getColumnModel().getColumn(1).setResizable(false);
            grille.getColumnModel().getColumn(2).setResizable(false);
            grille.getColumnModel().getColumn(3).setResizable(false);
            grille.getColumnModel().getColumn(4).setResizable(false);
            grille.getColumnModel().getColumn(5).setResizable(false);
            grille.getColumnModel().getColumn(6).setResizable(false);
            grille.getColumnModel().getColumn(7).setResizable(false);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grilleMouseClicked
        int row = grille.rowAtPoint(evt.getPoint());
        int col = grille.columnAtPoint(evt.getPoint());
        System.out.println(row + " " + col);
        plateau.addPion(row, col);
    }//GEN-LAST:event_grilleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grille;
    // End of variables declaration//GEN-END:variables
    private Plateau plateau;
}
